name: Build & deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run test
        run: yarn test

      # <BUILD>
      - name: Run stage build
        if: github.ref == 'refs/heads/stage'
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
          API_BASE_URL: ${{ secrets.STAGE_API_BASE_URL }}
          LINK_SSV_WEBAPP: ${{ secrets.STAGE_LINK_SSV_WEBAPP }}
          ANNOUNCEMENT: ${{ secrets.STAGE_ANNOUNCEMENT }}
          GOOGLE_TAG_SECRET: ${{ secrets.STAGE_GOOGLE_TAG_SECRET }}
        run: yarn build

      - name: Run prod build
        if: github.ref == 'refs/heads/main'
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
          API_BASE_URL: ${{ secrets.PROD_API_BASE_URL_V3 }}
          ANNOUNCEMENT: ${{ secrets.PROD_ANNOUNCEMENT }}
          LINK_SSV_WEBAPP: ${{ secrets.PROD_LINK_SSV_WEBAPP_V3 }}
          GOOGLE_TAG_SECRET: ${{ secrets.PROD_GOOGLE_TAG_SECRET_V3 }}
        run: yarn build
      # </BUILD>

      # <DEPLOY>
      - name: Deploy staging
        if: github.ref == 'refs/heads/stage'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
          AWS_S3_BUCKET: ${{ secrets.STAGE_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGE_AWS_SECRET_KEY_ID }}
          ANNOUNCEMENT: ${{ secrets.STAGE_ANNOUNCEMENT }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'build/'

      - name: Deploy prod
        if: github.ref == 'refs/heads/main'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
          AWS_S3_BUCKET: ${{ secrets.PROD_AWS_S3_BUCKET_V3 }}
          ANNOUNCEMENT: ${{ secrets.PROD_ANNOUNCEMENT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_SECRET_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'build/'
        # </DEPLOY>
